name: Hello Contributors

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, thanks for your issues, will be reviewed and get answers soon."
        pr-message: "Hello, thanks for contributing. Your Pull request will soon be reviewed."